FROM golang:1.23.4-alpine

WORKDIR /app
COPY cmd/producer ./cmd/producer
COPY internal ./internal

COPY go.mod go.sum ./
RUN go mod tidy

WORKDIR /app/cmd/producer
RUN go build -o /app/producer

ENTRYPOINT ["/app/producer"]
